import type { MatchUser } from '../store';

export type SeedProfile = MatchUser;

/**
 * Real-photo demo members (WhatsApp source packs, re-encoded at high JPEG quality).
 * Used so the swipe deck never feels empty when live Firestore is thin.
 */
export const SEED_PROFILES: SeedProfile[] = [
  {
    uid: 'wa-001',
    name: 'Zawadi',
    age: 24,
    gender: 'female',
    bio: 'Brunch person. Live benga on weekends. Looking for someone who actually texts back.',
    photos: ['/seed/wa/p01.jpg', '/seed/wa/p02.jpg'],
    location: { city: 'Nairobi', distanceLabel: '2 km away' },
    interests: ['Music', 'Food', 'Travel'],
    verified: true,
  },
  {
    uid: 'wa-002',
    name: 'Neema',
    age: 22,
    gender: 'female',
    bio: 'Soft life, hard boundaries. I cook better than I text.',
    photos: ['/seed/wa/p02.jpg'],
    location: { city: 'Nairobi', distanceLabel: '5 km away' },
    interests: ['Books', 'Fitness', 'Movies'],
    verified: true,
  },
  {
    uid: 'wa-003',
    name: 'Amina',
    age: 26,
    gender: 'female',
    bio: 'Campus, coffee, long walks. I will steal your hoodie.',
    photos: ['/seed/wa/p03.jpg'],
    location: { city: 'Mombasa', distanceLabel: '8 km away' },
    interests: ['Art', 'Travel', 'Food'],
    verified: true,
  },
  {
    uid: 'wa-004',
    name: 'Baraka',
    age: 25,
    gender: 'female',
    bio: 'Sunset swims and design Twitter. Zero drama, good playlists only.',
    photos: ['/seed/wa/p04.jpg', '/seed/wa/p05.jpg'],
    location: { city: 'Kisumu', distanceLabel: '7 km away' },
    interests: ['Food', 'Church', 'Music'],
    verified: false,
  },
  {
    uid: 'wa-005',
    name: 'Imani',
    age: 23,
    gender: 'female',
    bio: 'Nurse. Church on Sunday. If you can make ugali we are basically fine.',
    photos: ['/seed/wa/p05.jpg'],
    location: { city: 'Nakuru', distanceLabel: '4 km away' },
    interests: ['Football', 'Tech', 'Music'],
    verified: true,
  },
  {
    uid: 'wa-006',
    name: 'Nia',
    age: 27,
    gender: 'female',
    bio: 'Weekend hikes when the weather behaves. Dog auntie energy.',
    photos: ['/seed/wa/p06.jpg'],
    location: { city: 'Thika', distanceLabel: '12 km away' },
    interests: ['Fitness', 'Food', 'Travel'],
    verified: true,
  },
  {
    uid: 'wa-007',
    name: 'Sanaa',
    age: 24,
    gender: 'female',
    bio: 'I make playlists faster than plans. Swipe right if you like real conversation.',
    photos: ['/seed/wa/p07.jpg', '/seed/wa/p08.jpg'],
    location: { city: 'Eldoret', distanceLabel: '6 km away' },
    interests: ['Music', 'Books', 'Movies'],
    verified: true,
  },
  {
    uid: 'wa-008',
    name: 'Tumaini',
    age: 22,
    gender: 'female',
    bio: 'Bookstore regular. Kiswahili poetry > small talk.',
    photos: ['/seed/wa/p08.jpg'],
    location: { city: 'Nairobi', distanceLabel: '3 km away' },
    interests: ['Tech', 'Football', 'Coffee'],
    verified: false,
  },
  {
    uid: 'wa-009',
    name: 'Wanjala',
    age: 28,
    gender: 'female',
    bio: 'Sauti Sol still on rotation. Looking for a genuine hang, not pen pals.',
    photos: ['/seed/wa/p09.jpg'],
    location: { city: 'Nairobi', distanceLabel: '9 km away' },
    interests: ['Fashion', 'Food', 'Art'],
    verified: true,
  },
  {
    uid: 'wa-010',
    name: 'Zuri',
    age: 21,
    gender: 'female',
    bio: 'Part-time chef, full-time foodie. First date = nyama choma, obviously.',
    photos: ['/seed/wa/p10.jpg', '/seed/wa/p11.jpg'],
    location: { city: 'Meru', distanceLabel: '5 km away' },
    interests: ['Hiking', 'Photography', 'Music'],
    verified: true,
  },
  {
    uid: 'wa-011',
    name: 'Adhiambo',
    age: 26,
    gender: 'female',
    bio: 'Quiet bar over loud club. Ask me about my side project.',
    photos: ['/seed/wa/p11.jpg'],
    location: { city: 'Nairobi', distanceLabel: '1 km away' },
    interests: ['Cooking', 'Family', 'Church'],
    verified: true,
  },
  {
    uid: 'wa-012',
    name: 'Akinyi',
    age: 25,
    gender: 'female',
    bio: 'Trainer by day. I will drag you to the gym, kindly.',
    photos: ['/seed/wa/p12.jpg'],
    location: { city: 'Mombasa', distanceLabel: '15 km away' },
    interests: ['Dance', 'Movies', 'Food'],
    verified: false,
  },
  {
    uid: 'wa-013',
    name: 'Atieno',
    age: 24,
    gender: 'female',
    bio: 'Design nerd. I notice fonts in the wild. Sorry.',
    photos: ['/seed/wa/p13.jpg', '/seed/wa/p14.jpg'],
    location: { city: 'Nairobi', distanceLabel: '2 km away' },
    interests: ['Music', 'Food', 'Travel'],
    verified: true,
  },
  {
    uid: 'wa-014',
    name: 'Chiku',
    age: 23,
    gender: 'female',
    bio: 'Karura walks and long voice notes. Keep up.',
    photos: ['/seed/wa/p14.jpg'],
    location: { city: 'Nairobi', distanceLabel: '5 km away' },
    interests: ['Books', 'Fitness', 'Movies'],
    verified: true,
  },
  {
    uid: 'wa-015',
    name: 'Dalila',
    age: 27,
    gender: 'female',
    bio: 'I am here for something real. No married men, no games.',
    photos: ['/seed/wa/p15.jpg'],
    location: { city: 'Mombasa', distanceLabel: '8 km away' },
    interests: ['Art', 'Travel', 'Food'],
    verified: true,
  },
  {
    uid: 'wa-016',
    name: 'Eshe',
    age: 22,
    gender: 'female',
    bio: 'Swahili coast girl in the city. Seafood and slow evenings.',
    photos: ['/seed/wa/p16.jpg', '/seed/wa/p17.jpg'],
    location: { city: 'Kisumu', distanceLabel: '7 km away' },
    interests: ['Food', 'Church', 'Music'],
    verified: false,
  },
  {
    uid: 'wa-017',
    name: 'Farida',
    age: 29,
    gender: 'female',
    bio: 'Gym, journaling, early nights. Looking for peace and chemistry.',
    photos: ['/seed/wa/p17.jpg'],
    location: { city: 'Nakuru', distanceLabel: '4 km away' },
    interests: ['Football', 'Tech', 'Music'],
    verified: true,
  },
  {
    uid: 'wa-018',
    name: 'Halima',
    age: 24,
    gender: 'female',
    bio: 'I laugh too loud and I text too much. Deal with it.',
    photos: ['/seed/wa/p18.jpg'],
    location: { city: 'Thika', distanceLabel: '12 km away' },
    interests: ['Fitness', 'Food', 'Travel'],
    verified: true,
  },
  {
    uid: 'wa-019',
    name: 'Inaya',
    age: 21,
    gender: 'female',
    bio: 'Public health student. I will talk about water quality on our first date.',
    photos: ['/seed/wa/p19.jpg', '/seed/wa/p20.jpg'],
    location: { city: 'Eldoret', distanceLabel: '6 km away' },
    interests: ['Music', 'Books', 'Movies'],
    verified: true,
  },
  {
    uid: 'wa-020',
    name: 'Jabali',
    age: 26,
    gender: 'female',
    bio: 'Vintage thrifter. Let us find a gem at Toi Market together.',
    photos: ['/seed/wa/p20.jpg'],
    location: { city: 'Nairobi', distanceLabel: '3 km away' },
    interests: ['Tech', 'Football', 'Coffee'],
    verified: false,
  },
  {
    uid: 'wa-021',
    name: 'Kamaria',
    age: 25,
    gender: 'female',
    bio: 'Family first, ambition second, nonsense never.',
    photos: ['/seed/wa/p21.jpg'],
    location: { city: 'Nairobi', distanceLabel: '9 km away' },
    interests: ['Fashion', 'Food', 'Art'],
    verified: true,
  },
  {
    uid: 'wa-022',
    name: 'Layla',
    age: 23,
    gender: 'female',
    bio: 'I sing badly in traffic. Looking for a duet partner.',
    photos: ['/seed/wa/p22.jpg', '/seed/wa/p23.jpg'],
    location: { city: 'Meru', distanceLabel: '5 km away' },
    interests: ['Hiking', 'Photography', 'Music'],
    verified: true,
  },
  {
    uid: 'wa-023',
    name: 'Malaika',
    age: 22,
    gender: 'female',
    bio: 'Tech girlie. I fix my own Wi-Fi and my own mood.',
    photos: ['/seed/wa/p23.jpg'],
    location: { city: 'Nairobi', distanceLabel: '1 km away' },
    interests: ['Cooking', 'Family', 'Church'],
    verified: true,
  },
  {
    uid: 'wa-024',
    name: 'Njeri',
    age: 28,
    gender: 'female',
    bio: 'Football on the TV, chapati on the stove. That is the vibe.',
    photos: ['/seed/wa/p24.jpg'],
    location: { city: 'Mombasa', distanceLabel: '15 km away' },
    interests: ['Dance', 'Movies', 'Food'],
    verified: false,
  },
  {
    uid: 'wa-025',
    name: 'Pendo',
    age: 24,
    gender: 'female',
    bio: 'Short trips to Naivasha recharge me. Plan one with me.',
    photos: ['/seed/wa/p25.jpg', '/seed/wa/p26.jpg'],
    location: { city: 'Nairobi', distanceLabel: '2 km away' },
    interests: ['Music', 'Food', 'Travel'],
    verified: true,
  },
  {
    uid: 'wa-026',
    name: 'Rehema',
    age: 27,
    gender: 'female',
    bio: 'I am allergic to mixed signals. Be clear or be gone.',
    photos: ['/seed/wa/p26.jpg'],
    location: { city: 'Nairobi', distanceLabel: '5 km away' },
    interests: ['Books', 'Fitness', 'Movies'],
    verified: true,
  },
  {
    uid: 'wa-027',
    name: 'Salama',
    age: 25,
    gender: 'female',
    bio: 'Photographer. Yes, I will make you pose nicely.',
    photos: ['/seed/wa/p27.jpg'],
    location: { city: 'Mombasa', distanceLabel: '8 km away' },
    interests: ['Art', 'Travel', 'Food'],
    verified: true,
  },
  {
    uid: 'wa-028',
    name: 'Tamu',
    age: 23,
    gender: 'female',
    bio: 'Plant mum of seven. They all have names.',
    photos: ['/seed/wa/p28.jpg', '/seed/wa/p29.jpg'],
    location: { city: 'Kisumu', distanceLabel: '7 km away' },
    interests: ['Food', 'Church', 'Music'],
    verified: false,
  },
  {
    uid: 'wa-029',
    name: 'Uzuri',
    age: 26,
    gender: 'female',
    bio: 'Comedy podcasts and late-night mandazi. Join me.',
    photos: ['/seed/wa/p29.jpg'],
    location: { city: 'Nakuru', distanceLabel: '4 km away' },
    interests: ['Football', 'Tech', 'Music'],
    verified: true,
  },
  {
    uid: 'wa-030',
    name: 'Venus',
    age: 24,
    gender: 'female',
    bio: 'Working on my chest freezer of leftovers. Bring containers.',
    photos: ['/seed/wa/p30.jpg'],
    location: { city: 'Thika', distanceLabel: '12 km away' },
    interests: ['Fitness', 'Food', 'Travel'],
    verified: true,
  },
  {
    uid: 'wa-031',
    name: 'Wanjiru',
    age: 22,
    gender: 'female',
    bio: 'Introvert with excellent taste in men. Prove me right.',
    photos: ['/seed/wa/p31.jpg', '/seed/wa/p32.jpg'],
    location: { city: 'Eldoret', distanceLabel: '6 km away' },
    interests: ['Music', 'Books', 'Movies'],
    verified: true,
  },
  {
    uid: 'wa-032',
    name: 'Yusra',
    age: 25,
    gender: 'female',
    bio: 'I will remember your birthday and your coffee order.',
    photos: ['/seed/wa/p32.jpg'],
    location: { city: 'Nairobi', distanceLabel: '3 km away' },
    interests: ['Tech', 'Football', 'Coffee'],
    verified: false,
  },
  {
    uid: 'wa-033',
    name: 'Zaina',
    age: 27,
    gender: 'female',
    bio: 'Kisumu energy. Fish for dinner, lake breeze after.',
    photos: ['/seed/wa/p33.jpg'],
    location: { city: 'Nairobi', distanceLabel: '9 km away' },
    interests: ['Fashion', 'Food', 'Art'],
    verified: true,
  },
  {
    uid: 'wa-034',
    name: 'Amani',
    age: 24,
    gender: 'female',
    bio: 'Fashion when I feel like it, hoodie when I do not.',
    photos: ['/seed/wa/p34.jpg', '/seed/wa/p35.jpg'],
    location: { city: 'Meru', distanceLabel: '5 km away' },
    interests: ['Hiking', 'Photography', 'Music'],
    verified: true,
  },
  {
    uid: 'wa-035',
    name: 'Binti',
    age: 21,
    gender: 'female',
    bio: 'Looking for a best friend I can also kiss.',
    photos: ['/seed/wa/p35.jpg'],
    location: { city: 'Nairobi', distanceLabel: '1 km away' },
    interests: ['Cooking', 'Family', 'Church'],
    verified: true,
  },
  {
    uid: 'wa-036',
    name: 'Chepkoech',
    age: 28,
    gender: 'female',
    bio: 'Weekend market, then coffee, then see what happens.',
    photos: ['/seed/wa/p36.jpg'],
    location: { city: 'Mombasa', distanceLabel: '15 km away' },
    interests: ['Dance', 'Movies', 'Food'],
    verified: false,
  },
  {
    uid: 'wa-037',
    name: 'Deka',
    age: 23,
    gender: 'female',
    bio: 'I do not chase. I attract. And I cook.',
    photos: ['/seed/wa/p37.jpg', '/seed/wa/p38.jpg'],
    location: { city: 'Nairobi', distanceLabel: '2 km away' },
    interests: ['Music', 'Food', 'Travel'],
    verified: true,
  },
  {
    uid: 'wa-038',
    name: 'Fatuma',
    age: 26,
    gender: 'female',
    bio: 'Runner. I am slow but I finish. Same energy for relationships.',
    photos: ['/seed/wa/p38.jpg'],
    location: { city: 'Nairobi', distanceLabel: '5 km away' },
    interests: ['Books', 'Fitness', 'Movies'],
    verified: true,
  },
  {
    uid: 'wa-039',
    name: 'Gina',
    age: 24,
    gender: 'female',
    bio: 'Spoken word nights. Come listen with me.',
    photos: ['/seed/wa/p39.jpg'],
    location: { city: 'Mombasa', distanceLabel: '8 km away' },
    interests: ['Art', 'Travel', 'Food'],
    verified: true,
  },
  {
    uid: 'wa-040',
    name: 'Hodan',
    age: 25,
    gender: 'female',
    bio: 'I keep plants alive and plants keep me honest.',
    photos: ['/seed/wa/p40.jpg', '/seed/wa/p41.jpg'],
    location: { city: 'Kisumu', distanceLabel: '7 km away' },
    interests: ['Food', 'Church', 'Music'],
    verified: false,
  },
  {
    uid: 'wa-041',
    name: 'Ivy',
    age: 22,
    gender: 'female',
    bio: 'Ask me about my trip to Watamu. I will show photos.',
    photos: ['/seed/wa/p41.jpg'],
    location: { city: 'Nakuru', distanceLabel: '4 km away' },
    interests: ['Football', 'Tech', 'Music'],
    verified: true,
  },
  {
    uid: 'wa-042',
    name: 'Joan',
    age: 27,
    gender: 'female',
    bio: 'Baking stress-relief cookies for the office again.',
    photos: ['/seed/wa/p42.jpg'],
    location: { city: 'Thika', distanceLabel: '12 km away' },
    interests: ['Fitness', 'Food', 'Travel'],
    verified: true,
  },
  {
    uid: 'wa-043',
    name: 'Kawira',
    age: 24,
    gender: 'female',
    bio: 'Old soul. Highlife and cool evenings.',
    photos: ['/seed/wa/p43.jpg', '/seed/wa/p44.jpg'],
    location: { city: 'Eldoret', distanceLabel: '6 km away' },
    interests: ['Music', 'Books', 'Movies'],
    verified: true,
  },
  {
    uid: 'wa-044',
    name: 'Linda',
    age: 23,
    gender: 'female',
    bio: 'I like my men like my tea: strong and not bitter.',
    photos: ['/seed/wa/p44.jpg'],
    location: { city: 'Nairobi', distanceLabel: '3 km away' },
    interests: ['Tech', 'Football', 'Coffee'],
    verified: false,
  },
  {
    uid: 'wa-045',
    name: 'Mariam',
    age: 29,
    gender: 'female',
    bio: 'Mama mboga of my own destiny.',
    photos: ['/seed/wa/p45.jpg'],
    location: { city: 'Nairobi', distanceLabel: '9 km away' },
    interests: ['Fashion', 'Food', 'Art'],
    verified: true,
  },
  {
    uid: 'wa-046',
    name: 'Naomi',
    age: 25,
    gender: 'female',
    bio: 'Sunday meal prep looking for a sous-chef.',
    photos: ['/seed/wa/p46.jpg', '/seed/wa/p47.jpg'],
    location: { city: 'Meru', distanceLabel: '5 km away' },
    interests: ['Hiking', 'Photography', 'Music'],
    verified: true,
  },
  {
    uid: 'wa-047',
    name: 'Onyango',
    age: 24,
    gender: 'female',
    bio: 'Dance when nobody is watching. Also when they are.',
    photos: ['/seed/wa/p47.jpg'],
    location: { city: 'Nairobi', distanceLabel: '1 km away' },
    interests: ['Cooking', 'Family', 'Church'],
    verified: true,
  },
  {
    uid: 'wa-048',
    name: 'Precious',
    age: 22,
    gender: 'female',
    bio: 'Direct, warm, slightly chaotic. You will never be bored.',
    photos: ['/seed/wa/p48.jpg'],
    location: { city: 'Mombasa', distanceLabel: '15 km away' },
    interests: ['Dance', 'Movies', 'Food'],
    verified: false,
  },
  {
    uid: 'wa-049',
    name: 'Quinter',
    age: 26,
    gender: 'female',
    bio: 'I believe in second dates and good lighting.',
    photos: ['/seed/wa/p49.jpg', '/seed/wa/p50.jpg'],
    location: { city: 'Nairobi', distanceLabel: '2 km away' },
    interests: ['Music', 'Food', 'Travel'],
    verified: true,
  },
  {
    uid: 'wa-050',
    name: 'Rosa',
    age: 25,
    gender: 'female',
    bio: 'Here for long walks and longer conversations.',
    photos: ['/seed/wa/p50.jpg'],
    location: { city: 'Nairobi', distanceLabel: '5 km away' },
    interests: ['Books', 'Fitness', 'Movies'],
    verified: true,
  },
  {
    uid: 'wa-051',
    name: 'Sheila',
    age: 24,
    gender: 'female',
    bio: 'Analyst by weekday, thrill-seeker by weekend.',
    photos: ['/seed/wa/p51.jpg'],
    location: { city: 'Mombasa', distanceLabel: '8 km away' },
    interests: ['Art', 'Travel', 'Food'],
    verified: true,
  },
  {
    uid: 'wa-052',
    name: 'Tasha',
    age: 23,
    gender: 'female',
    bio: 'I will make you playlist for every mood.',
    photos: ['/seed/wa/p52.jpg', '/seed/wa/p53.jpg'],
    location: { city: 'Kisumu', distanceLabel: '7 km away' },
    interests: ['Food', 'Church', 'Music'],
    verified: false,
  },
  {
    uid: 'wa-053',
    name: 'Upendo',
    age: 27,
    gender: 'female',
    bio: 'Looking for kindness first. Attraction second. Luggage never.',
    photos: ['/seed/wa/p53.jpg'],
    location: { city: 'Nakuru', distanceLabel: '4 km away' },
    interests: ['Football', 'Tech', 'Music'],
    verified: true,
  },
  {
    uid: 'wa-054',
    name: 'Valentine',
    age: 24,
    gender: 'female',
    bio: 'Chapati night is sacred. Respect it.',
    photos: ['/seed/wa/p54.jpg'],
    location: { city: 'Thika', distanceLabel: '12 km away' },
    interests: ['Fitness', 'Food', 'Travel'],
    verified: true,
  },
  {
    uid: 'wa-055',
    name: 'Winnie',
    age: 22,
    gender: 'female',
    bio: 'Gentle heart, sharp mind, terrible at waiting.',
    photos: ['/seed/wa/p55.jpg', '/seed/wa/p56.jpg'],
    location: { city: 'Eldoret', distanceLabel: '6 km away' },
    interests: ['Music', 'Books', 'Movies'],
    verified: true,
  },
  {
    uid: 'wa-056',
    name: 'Xena',
    age: 25,
    gender: 'female',
    bio: 'I travel light and laugh heavy.',
    photos: ['/seed/wa/p56.jpg'],
    location: { city: 'Nairobi', distanceLabel: '3 km away' },
    interests: ['Tech', 'Football', 'Coffee'],
    verified: false,
  },
  {
    uid: 'wa-057',
    name: 'Yvonne',
    age: 26,
    gender: 'female',
    bio: 'Surprise me with food and we are good.',
    photos: ['/seed/wa/p57.jpg'],
    location: { city: 'Nairobi', distanceLabel: '9 km away' },
    interests: ['Fashion', 'Food', 'Art'],
    verified: true,
  },
  {
    uid: 'wa-058',
    name: 'Zawadi M',
    age: 24,
    gender: 'female',
    bio: 'I take my coffee black and my men honest.',
    photos: ['/seed/wa/p58.jpg', '/seed/wa/p59.jpg'],
    location: { city: 'Meru', distanceLabel: '5 km away' },
    interests: ['Hiking', 'Photography', 'Music'],
    verified: true,
  },
  {
    uid: 'wa-059',
    name: 'Achieng',
    age: 25,
    gender: 'female',
    bio: 'Karaoke in the car is non-negotiable.',
    photos: ['/seed/wa/p59.jpg'],
    location: { city: 'Nairobi', distanceLabel: '1 km away' },
    interests: ['Cooking', 'Family', 'Church'],
    verified: true,
  },
  {
    uid: 'wa-060',
    name: 'Beverly',
    age: 23,
    gender: 'female',
    bio: 'Beach over mountains. Tired over lies.',
    photos: ['/seed/wa/p60.jpg'],
    location: { city: 'Mombasa', distanceLabel: '15 km away' },
    interests: ['Dance', 'Movies', 'Food'],
    verified: false,
  },
  {
    uid: 'wa-061',
    name: 'Cynthia',
    age: 27,
    gender: 'female',
    bio: 'I am building a quiet life with loud joy in it.',
    photos: ['/seed/wa/p61.jpg', '/seed/wa/p62.jpg'],
    location: { city: 'Nairobi', distanceLabel: '2 km away' },
    interests: ['Music', 'Food', 'Travel'],
    verified: true,
  },
  {
    uid: 'wa-062',
    name: 'Doris',
    age: 24,
    gender: 'female',
    bio: 'Curly hair, full schedule, open heart.',
    photos: ['/seed/wa/p62.jpg'],
    location: { city: 'Nairobi', distanceLabel: '5 km away' },
    interests: ['Books', 'Fitness', 'Movies'],
    verified: true,
  },
  {
    uid: 'wa-063',
    name: 'Edith',
    age: 22,
    gender: 'female',
    bio: 'Ask me anything except my body count.',
    photos: ['/seed/wa/p63.jpg'],
    location: { city: 'Mombasa', distanceLabel: '8 km away' },
    interests: ['Art', 'Travel', 'Food'],
    verified: true,
  },
  {
    uid: 'wa-064',
    name: 'Faith',
    age: 25,
    gender: 'female',
    bio: 'I want a love that feels like home-cooked food.',
    photos: ['/seed/wa/p64.jpg', '/seed/wa/p65.jpg'],
    location: { city: 'Kisumu', distanceLabel: '7 km away' },
    interests: ['Food', 'Church', 'Music'],
    verified: false,
  },
  {
    uid: 'wa-065',
    name: 'Gloria',
    age: 24,
    gender: 'female',
    bio: 'Weekend farmer market and a good film. That is a date.',
    photos: ['/seed/wa/p65.jpg'],
    location: { city: 'Nakuru', distanceLabel: '4 km away' },
    interests: ['Football', 'Tech', 'Music'],
    verified: true,
  },
  {
    uid: 'wa-066',
    name: 'Hilda',
    age: 28,
    gender: 'female',
    bio: 'I work hard so we can play harder. Responsibly.',
    photos: ['/seed/wa/p66.jpg'],
    location: { city: 'Thika', distanceLabel: '12 km away' },
    interests: ['Fitness', 'Food', 'Travel'],
    verified: true,
  },
  {
    uid: 'wa-067',
    name: 'Irene',
    age: 23,
    gender: 'female',
    bio: 'Honesty is my love language. The rest is negotiable.',
    photos: ['/seed/wa/p67.jpg', '/seed/wa/p68.jpg'],
    location: { city: 'Eldoret', distanceLabel: '6 km away' },
    interests: ['Music', 'Books', 'Movies'],
    verified: true,
  },
  {
    uid: 'wa-068',
    name: 'Joy',
    age: 24,
    gender: 'female',
    bio: 'Looking for chemistry and consistency.',
    photos: ['/seed/wa/p68.jpg'],
    location: { city: 'Nairobi', distanceLabel: '3 km away' },
    interests: ['Tech', 'Football', 'Coffee'],
    verified: false,
  },
  {
    uid: 'wa-069',
    name: 'Keziah',
    age: 22,
    gender: 'female',
    bio: 'I will drive if you navigate. Teamwork.',
    photos: ['/seed/wa/p69.jpg'],
    location: { city: 'Nairobi', distanceLabel: '9 km away' },
    interests: ['Fashion', 'Food', 'Art'],
    verified: true,
  },
  {
    uid: 'wa-070',
    name: 'Linet',
    age: 26,
    gender: 'female',
    bio: 'Street food critic in my spare time.',
    photos: ['/seed/wa/p70.jpg', '/seed/wa/p71.jpg'],
    location: { city: 'Meru', distanceLabel: '5 km away' },
    interests: ['Hiking', 'Photography', 'Music'],
    verified: true,
  },
  {
    uid: 'wa-071',
    name: 'Mercy',
    age: 25,
    gender: 'female',
    bio: 'I believe couples who laugh together last.',
    photos: ['/seed/wa/p71.jpg'],
    location: { city: 'Nairobi', distanceLabel: '1 km away' },
    interests: ['Cooking', 'Family', 'Church'],
    verified: true,
  },
  {
    uid: 'wa-072',
    name: 'Nancy',
    age: 24,
    gender: 'female',
    bio: 'Soft heart. I cry at ads sometimes.',
    photos: ['/seed/wa/p72.jpg'],
    location: { city: 'Mombasa', distanceLabel: '15 km away' },
    interests: ['Dance', 'Movies', 'Food'],
    verified: false,
  },
  {
    uid: 'wa-073',
    name: 'Olive',
    age: 27,
    gender: 'female',
    bio: 'Bring me a book and I am yours forever.',
    photos: ['/seed/wa/p73.jpg', '/seed/wa/p74.jpg'],
    location: { city: 'Nairobi', distanceLabel: '2 km away' },
    interests: ['Music', 'Food', 'Travel'],
    verified: true,
  },
  {
    uid: 'wa-074',
    name: 'Purity',
    age: 23,
    gender: 'female',
    bio: 'I want someone who texts first sometimes.',
    photos: ['/seed/wa/p74.jpg'],
    location: { city: 'Nairobi', distanceLabel: '5 km away' },
    interests: ['Books', 'Fitness', 'Movies'],
    verified: true,
  },
  {
    uid: 'wa-075',
    name: 'Queen',
    age: 24,
    gender: 'female',
    bio: 'Swahili food, coastal breeze, good company.',
    photos: ['/seed/wa/p75.jpg'],
    location: { city: 'Mombasa', distanceLabel: '8 km away' },
    interests: ['Art', 'Travel', 'Food'],
    verified: true,
  },
  {
    uid: 'wa-076',
    name: 'Rachael',
    age: 25,
    gender: 'female',
    bio: 'Ambitious, warm, and done with games.',
    photos: ['/seed/wa/p76.jpg', '/seed/wa/p77.jpg'],
    location: { city: 'Kisumu', distanceLabel: '7 km away' },
    interests: ['Food', 'Church', 'Music'],
    verified: false,
  },
  {
    uid: 'wa-077',
    name: 'Susan',
    age: 22,
    gender: 'female',
    bio: 'I smile at strangers and mean it.',
    photos: ['/seed/wa/p77.jpg'],
    location: { city: 'Nakuru', distanceLabel: '4 km away' },
    interests: ['Football', 'Tech', 'Music'],
    verified: true,
  },
  {
    uid: 'wa-078',
    name: 'Tabitha',
    age: 28,
    gender: 'female',
    bio: 'Looking for a real one in a fake world.',
    photos: ['/seed/wa/p78.jpg'],
    location: { city: 'Thika', distanceLabel: '12 km away' },
    interests: ['Fitness', 'Food', 'Travel'],
    verified: true,
  },
  {
    uid: 'wa-079',
    name: 'Ummi',
    age: 24,
    gender: 'female',
    bio: 'Gym girl who also loves cake. Balance.',
    photos: ['/seed/wa/p79.jpg', '/seed/wa/p80.jpg'],
    location: { city: 'Eldoret', distanceLabel: '6 km away' },
    interests: ['Music', 'Books', 'Movies'],
    verified: true,
  },
  {
    uid: 'wa-080',
    name: 'Vera',
    age: 26,
    gender: 'female',
    bio: 'I keep plants and boundaries healthy.',
    photos: ['/seed/wa/p80.jpg'],
    location: { city: 'Nairobi', distanceLabel: '3 km away' },
    interests: ['Tech', 'Football', 'Coffee'],
    verified: false,
  },
  {
    uid: 'wa-081',
    name: 'Wairimu',
    age: 25,
    gender: 'female',
    bio: 'Here for a best friend with benefits of respect.',
    photos: ['/seed/wa/p81.jpg'],
    location: { city: 'Nairobi', distanceLabel: '9 km away' },
    interests: ['Fashion', 'Food', 'Art'],
    verified: true,
  },
  {
    uid: 'wa-082',
    name: 'Yvone',
    age: 23,
    gender: 'female',
    bio: 'I take photos of food more than people.',
    photos: ['/seed/wa/p82.jpg', '/seed/wa/p83.jpg'],
    location: { city: 'Meru', distanceLabel: '5 km away' },
    interests: ['Hiking', 'Photography', 'Music'],
    verified: true,
  },
  {
    uid: 'wa-083',
    name: 'Zena',
    age: 24,
    gender: 'female',
    bio: 'Quiet confidence. Loud laugh.',
    photos: ['/seed/wa/p83.jpg'],
    location: { city: 'Nairobi', distanceLabel: '1 km away' },
    interests: ['Cooking', 'Family', 'Church'],
    verified: true,
  },
  {
    uid: 'wa-084',
    name: 'Awino',
    age: 22,
    gender: 'female',
    bio: 'Let us skip the small talk and talk about dreams.',
    photos: ['/seed/wa/p84.jpg'],
    location: { city: 'Mombasa', distanceLabel: '15 km away' },
    interests: ['Dance', 'Movies', 'Food'],
    verified: false,
  },
  {
    uid: 'wa-085',
    name: 'Brilliant',
    age: 27,
    gender: 'female',
    bio: 'I love a man with a plan and a joke.',
    photos: ['/seed/wa/p85.jpg', '/seed/wa/p86.jpg'],
    location: { city: 'Nairobi', distanceLabel: '2 km away' },
    interests: ['Music', 'Food', 'Travel'],
    verified: true,
  },
  {
    uid: 'wa-086',
    name: 'Caroline',
    age: 24,
    gender: 'female',
    bio: 'Sundays are for family and ugali.',
    photos: ['/seed/wa/p86.jpg'],
    location: { city: 'Nairobi', distanceLabel: '5 km away' },
    interests: ['Books', 'Fitness', 'Movies'],
    verified: true,
  },
  {
    uid: 'wa-087',
    name: 'Diana',
    age: 25,
    gender: 'female',
    bio: 'I dance while cooking. Safety hazard included.',
    photos: ['/seed/wa/p87.jpg'],
    location: { city: 'Mombasa', distanceLabel: '8 km away' },
    interests: ['Art', 'Travel', 'Food'],
    verified: true,
  },
  {
    uid: 'wa-088',
    name: 'Eunice',
    age: 23,
    gender: 'female',
    bio: 'Looking for effort, not perfection.',
    photos: ['/seed/wa/p88.jpg', '/seed/wa/p89.jpg'],
    location: { city: 'Kisumu', distanceLabel: '7 km away' },
    interests: ['Food', 'Church', 'Music'],
    verified: false,
  },
  {
    uid: 'wa-089',
    name: 'Fridah',
    age: 26,
    gender: 'female',
    bio: 'I will remember how you like your tea.',
    photos: ['/seed/wa/p89.jpg'],
    location: { city: 'Nakuru', distanceLabel: '4 km away' },
    interests: ['Football', 'Tech', 'Music'],
    verified: true,
  },
  {
    uid: 'wa-090',
    name: 'Grace',
    age: 24,
    gender: 'female',
    bio: 'Energy matches only. If you are dry, keep scrolling.',
    photos: ['/seed/wa/p90.jpg'],
    location: { city: 'Thika', distanceLabel: '12 km away' },
    interests: ['Fitness', 'Food', 'Travel'],
    verified: true,
  },
  {
    uid: 'wa-091',
    name: 'Happiness',
    age: 22,
    gender: 'female',
    bio: 'Music, food, and peace. That is my brand.',
    photos: ['/seed/wa/p91.jpg', '/seed/wa/p92.jpg'],
    location: { city: 'Eldoret', distanceLabel: '6 km away' },
    interests: ['Music', 'Books', 'Movies'],
    verified: true,
  },
  {
    uid: 'wa-092',
    name: 'Ida',
    age: 25,
    gender: 'female',
    bio: 'I am the friend who actually replies.',
    photos: ['/seed/wa/p92.jpg'],
    location: { city: 'Nairobi', distanceLabel: '3 km away' },
    interests: ['Tech', 'Football', 'Coffee'],
    verified: false,
  },
  {
    uid: 'wa-093',
    name: 'Jackie',
    age: 27,
    gender: 'female',
    bio: 'Born curious, raised kind, still learning.',
    photos: ['/seed/wa/p93.jpg'],
    location: { city: 'Nairobi', distanceLabel: '9 km away' },
    interests: ['Fashion', 'Food', 'Art'],
    verified: true,
  },
  {
    uid: 'wa-094',
    name: 'Kadzo',
    age: 24,
    gender: 'female',
    bio: 'Looking for someone to spoil me with attention.',
    photos: ['/seed/wa/p94.jpg', '/seed/wa/p95.jpg'],
    location: { city: 'Meru', distanceLabel: '5 km away' },
    interests: ['Hiking', 'Photography', 'Music'],
    verified: true,
  },
  {
    uid: 'wa-095',
    name: 'Lilian',
    age: 23,
    gender: 'female',
    bio: 'Road trips and wrong turns are fine by me.',
    photos: ['/seed/wa/p95.jpg'],
    location: { city: 'Nairobi', distanceLabel: '1 km away' },
    interests: ['Cooking', 'Family', 'Church'],
    verified: true,
  },
  {
    uid: 'wa-096',
    name: 'Maureen',
    age: 25,
    gender: 'female',
    bio: 'I cry at happy endings. You have been warned.',
    photos: ['/seed/wa/p96.jpg'],
    location: { city: 'Mombasa', distanceLabel: '15 km away' },
    interests: ['Dance', 'Movies', 'Food'],
    verified: false,
  },
  {
    uid: 'wa-097',
    name: 'Natasha',
    age: 24,
    gender: 'female',
    bio: 'My love language is acts of service and snacks.',
    photos: ['/seed/wa/p97.jpg', '/seed/wa/p98.jpg'],
    location: { city: 'Nairobi', distanceLabel: '2 km away' },
    interests: ['Music', 'Food', 'Travel'],
    verified: true,
  },
  {
    uid: 'wa-098',
    name: 'Ocholla',
    age: 28,
    gender: 'female',
    bio: 'Here for a man who knows what he wants.',
    photos: ['/seed/wa/p98.jpg'],
    location: { city: 'Nairobi', distanceLabel: '5 km away' },
    interests: ['Books', 'Fitness', 'Movies'],
    verified: true,
  },
  {
    uid: 'wa-099',
    name: 'Pamela',
    age: 22,
    gender: 'female',
    bio: 'I make a living and a life. Join both.',
    photos: ['/seed/wa/p99.jpg'],
    location: { city: 'Mombasa', distanceLabel: '8 km away' },
    interests: ['Art', 'Travel', 'Food'],
    verified: true,
  },
  {
    uid: 'wa-100',
    name: 'Rita',
    age: 25,
    gender: 'female',
    bio: 'Romantic but realistic. Swipe if that sounds like you.',
    photos: ['/seed/wa/p100.jpg', '/seed/wa/p101.jpg'],
    location: { city: 'Kisumu', distanceLabel: '7 km away' },
    interests: ['Food', 'Church', 'Music'],
    verified: false,
  },
  {
    uid: 'wa-101',
    name: 'Sharleen',
    age: 24,
    gender: 'female',
    bio: 'I will cook if you clean. Fair trade.',
    photos: ['/seed/wa/p101.jpg'],
    location: { city: 'Nakuru', distanceLabel: '4 km away' },
    interests: ['Football', 'Tech', 'Music'],
    verified: true,
  },
];

export function filterSeeds(
  filters: {
    interestedIn: 'men' | 'women' | 'everyone';
    minAge: number;
    maxAge: number;
    city?: string;
  },
  excludeUids: string[]
): SeedProfile[] {
  const exclude = new Set(excludeUids);
  return SEED_PROFILES.filter((p) => {
    if (exclude.has(p.uid)) return false;
    if (filters.interestedIn === 'men' && p.gender !== 'male') return false;
    if (filters.interestedIn === 'women' && p.gender !== 'female') return false;
    if (p.age < filters.minAge || p.age > filters.maxAge) return false;
    if (filters.city && p.location?.city !== filters.city) return false;
    return true;
  });
}
